Fix generated code of default value was "0.0" at float field.
If schema has float field, get error below:
error: incompatible types: possible lossy conversion from double to float
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output

Generated code is below:
  public float getProgress() {
    return getFloat("progress", 0.0);
  }

This happens to pass default value by Object on SchemaWriter.
So I change to pass default value by String.